# Blog
keywords: Hexo,Blog
author: 垚
description: (✿╹◡╹) 相信的心就是你的魔法 (╹◡╹✿)
avatar: /images/favicon.png

# Site
title: 无存在感小透明
subtitle: (✿╹◡╹) 相信的心就是你的魔法 (╹◡╹✿)
language: zh-CN
timezone: Asia/Shanghai

# Social Accounts
twitter: 
instagram: 
weibo: 
facebook: 
github: 
telegram: 
email: 
rss: 
rss_rss2: rss2.xml
rss_atom: atom.xml

# Comment
duoshuo: 
disqus: 
gentie: 
# Valine Comment https://valine.js.org
valine:
  enable: false # Set true if you want to use valine
  app_id: # Your LeanCloud AppID
  app_key: # Your LeanCloud AppKey
  placeholder: Just go go # Comment box placeholder
  avatar: mp # Avatar style https://valine.js.org/avatar.html
  visitor: false # Article reading statistics https://valine.js.org/visitor.html
  record_ip: false # Record reviewer IP
  server_urls: # Your LeanCloud REST API Server URL
utterances:
  # if you want to use utterance, please set the repo to your github repository to hold the comments
  #repo: user/repo
